#!/usr/bin/env python3
# Script to generate icons.h header file from lib/bitmap_images/ directory.
# Scans the actual bitmap headers to produce a unified enum and getBitmap() function.
#
# Usage:
#   python3 final_generate_icons_h.py
#
# Output:
#   ../lib/bitmap_images/icons.h

import os

BITMAP_DIR = os.path.join(os.path.dirname(__file__), '..', 'lib', 'bitmap_images')
SIZES = [16, 24, 32, 48, 64]
OUTPUT_FILE = os.path.join(BITMAP_DIR, 'icons.h')

# Icons referenced in code but without bitmap data for all sizes.
# getBitmap() returns nullptr for these — calling code handles that gracefully.
ENUM_ONLY_ICONS = [
    'RMV_Logo',
    'battery_alert_0deg',
    'battery_charging_full_90deg',
]


def get_icon_names():
    """Collect icon names that exist in ALL size directories."""
    icons_per_size = {}
    for size in SIZES:
        size_dir = os.path.join(BITMAP_DIR, f'{size}x{size}')
        if not os.path.isdir(size_dir):
            continue
        suffix = f'_{size}x{size}.h'
        names = set()
        for f in os.listdir(size_dir):
            if f.endswith(suffix):
                names.add(f[:-len(suffix)])
        icons_per_size[size] = names

    # Only include icons present in ALL sizes
    all_icons = set.intersection(*icons_per_size.values()) if icons_per_size else set()
    return sorted(all_icons)


def generate_size_headers():
    """Regenerate icons_NxN.h from actual files in each size directory."""
    for size in SIZES:
        size_dir = os.path.join(BITMAP_DIR, f'{size}x{size}')
        header_file = os.path.join(BITMAP_DIR, f'icons_{size}x{size}.h')
        if not os.path.isdir(size_dir):
            continue
        headers = sorted(f for f in os.listdir(size_dir) if f.endswith('.h'))
        with open(header_file, 'w') as f:
            f.write(f'#ifndef __ICONS_{size}x{size}_H__\n')
            f.write(f'#define __ICONS_{size}x{size}_H__\n')
            for h in headers:
                f.write(f'#include "{size}x{size}/{h}"\n')
            f.write('#endif\n')


def generate_icons_h():
    generate_size_headers()
    icon_names = get_icon_names()

    lines = []
    lines.append('// DO NOT MODIFY -- THIS FILE WAS GENERATED BY `python3 final_generate_icons_h.py`')
    lines.append('')
    lines.append('#ifndef __ICONS_H__')
    lines.append('#define __ICONS_H__')
    lines.append('')
    lines.append('#include <cstddef>')
    lines.append('')

    for size in SIZES:
        lines.append(f'#include "icons_{size}x{size}.h"')
    lines.append('')

    # Enum — includes both real icons and enum-only placeholders
    all_enum_names = sorted(icon_names + ENUM_ONLY_ICONS)
    lines.append('typedef enum icon_name {')
    for name in all_enum_names:
        lines.append(f'  {name},')
    lines.append('} icon_name_t;')
    lines.append('')

    # getBitmap function
    lines.append('inline const unsigned char* getBitmap(icon_name_t icon, size_t size)')
    lines.append('{')
    lines.append('  switch (icon) {')
    for name in icon_names:
        lines.append(f'  case {name}:')
        lines.append('    switch (size) {')
        for size in SIZES:
            lines.append(f'    case {size}: return {name}_{size}x{size};')
        lines.append('    default:')
        lines.append('      return nullptr;')
        lines.append('    }')
    lines.append('  default:')
    lines.append('    return nullptr;')
    lines.append('  }')
    lines.append('}')
    lines.append('')
    lines.append('#endif')

    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"icons.h generated at {OUTPUT_FILE}")
    print(f"  {len(icon_names)} icons, {len(SIZES)} sizes")


if __name__ == '__main__':
    generate_icons_h()
