// DO NOT MODIFY -- THIS FILE WAS GENERATED BY `python3 final_generate_icons_h.py`

#ifndef __ICONS_H__
#define __ICONS_H__

#include <cstddef>

#include "icons_16x16.h"
#include "icons_24x24.h"
#include "icons_32x32.h"
#include "icons_48x48.h"
#include "icons_64x64.h"

typedef enum icon_name {
  Battery_1,
  Battery_2,
  Battery_3,
  Battery_4,
  Battery_5,
  RMV_Logo,
  battery_alert_0deg,
  battery_charging_full_90deg,
  refresh,
  wi_0_day_sunny,
  wi_1_day_sunny_overcast,
  wi_45_day_fog,
  wi_51_rain_mix,
  wi_56_rain_mix,
  wi_61_rain,
  wi_66_rain_mix,
  wi_71_snow_wind,
  wi_77_day_snow_wind,
  wi_81_showers,
  wi_85_snow_wind,
  wi_95_thunderstorm,
  wi_99_thunderstorm,
  wi_cloud_down,
  wi_moon_alt_full,
  wi_moon_alt_third_quarter,
  wi_moon_alt_waning_crescent_4,
  wi_moon_alt_waning_crescent_5,
  wi_moon_alt_waning_crescent_6,
  wi_moon_alt_waning_gibbous_1,
  wi_moon_alt_waning_gibbous_2,
  wi_moon_alt_waning_gibbous_3,
  wi_moon_alt_waning_gibbous_4,
  wi_moon_alt_waning_gibbous_5,
  wi_moon_alt_waning_gibbous_6,
  wi_moon_full,
  wi_strong_wind,
  wi_sunrise,
  wi_sunset,
  wi_time_5,
  wifi,
  wifi_1_bar,
  wifi_2_bar,
  wifi_3_bar,
  wifi_off,
} icon_name_t;

inline const unsigned char* getBitmap(icon_name_t icon, size_t size)
{
  switch (icon) {
  case Battery_1:
    switch (size) {
    case 16: return Battery_1_16x16;
    case 24: return Battery_1_24x24;
    case 32: return Battery_1_32x32;
    case 48: return Battery_1_48x48;
    case 64: return Battery_1_64x64;
    default:
      return nullptr;
    }
  case Battery_2:
    switch (size) {
    case 16: return Battery_2_16x16;
    case 24: return Battery_2_24x24;
    case 32: return Battery_2_32x32;
    case 48: return Battery_2_48x48;
    case 64: return Battery_2_64x64;
    default:
      return nullptr;
    }
  case Battery_3:
    switch (size) {
    case 16: return Battery_3_16x16;
    case 24: return Battery_3_24x24;
    case 32: return Battery_3_32x32;
    case 48: return Battery_3_48x48;
    case 64: return Battery_3_64x64;
    default:
      return nullptr;
    }
  case Battery_4:
    switch (size) {
    case 16: return Battery_4_16x16;
    case 24: return Battery_4_24x24;
    case 32: return Battery_4_32x32;
    case 48: return Battery_4_48x48;
    case 64: return Battery_4_64x64;
    default:
      return nullptr;
    }
  case Battery_5:
    switch (size) {
    case 16: return Battery_5_16x16;
    case 24: return Battery_5_24x24;
    case 32: return Battery_5_32x32;
    case 48: return Battery_5_48x48;
    case 64: return Battery_5_64x64;
    default:
      return nullptr;
    }
  case refresh:
    switch (size) {
    case 16: return refresh_16x16;
    case 24: return refresh_24x24;
    case 32: return refresh_32x32;
    case 48: return refresh_48x48;
    case 64: return refresh_64x64;
    default:
      return nullptr;
    }
  case wi_0_day_sunny:
    switch (size) {
    case 16: return wi_0_day_sunny_16x16;
    case 24: return wi_0_day_sunny_24x24;
    case 32: return wi_0_day_sunny_32x32;
    case 48: return wi_0_day_sunny_48x48;
    case 64: return wi_0_day_sunny_64x64;
    default:
      return nullptr;
    }
  case wi_1_day_sunny_overcast:
    switch (size) {
    case 16: return wi_1_day_sunny_overcast_16x16;
    case 24: return wi_1_day_sunny_overcast_24x24;
    case 32: return wi_1_day_sunny_overcast_32x32;
    case 48: return wi_1_day_sunny_overcast_48x48;
    case 64: return wi_1_day_sunny_overcast_64x64;
    default:
      return nullptr;
    }
  case wi_45_day_fog:
    switch (size) {
    case 16: return wi_45_day_fog_16x16;
    case 24: return wi_45_day_fog_24x24;
    case 32: return wi_45_day_fog_32x32;
    case 48: return wi_45_day_fog_48x48;
    case 64: return wi_45_day_fog_64x64;
    default:
      return nullptr;
    }
  case wi_51_rain_mix:
    switch (size) {
    case 16: return wi_51_rain_mix_16x16;
    case 24: return wi_51_rain_mix_24x24;
    case 32: return wi_51_rain_mix_32x32;
    case 48: return wi_51_rain_mix_48x48;
    case 64: return wi_51_rain_mix_64x64;
    default:
      return nullptr;
    }
  case wi_56_rain_mix:
    switch (size) {
    case 16: return wi_56_rain_mix_16x16;
    case 24: return wi_56_rain_mix_24x24;
    case 32: return wi_56_rain_mix_32x32;
    case 48: return wi_56_rain_mix_48x48;
    case 64: return wi_56_rain_mix_64x64;
    default:
      return nullptr;
    }
  case wi_61_rain:
    switch (size) {
    case 16: return wi_61_rain_16x16;
    case 24: return wi_61_rain_24x24;
    case 32: return wi_61_rain_32x32;
    case 48: return wi_61_rain_48x48;
    case 64: return wi_61_rain_64x64;
    default:
      return nullptr;
    }
  case wi_66_rain_mix:
    switch (size) {
    case 16: return wi_66_rain_mix_16x16;
    case 24: return wi_66_rain_mix_24x24;
    case 32: return wi_66_rain_mix_32x32;
    case 48: return wi_66_rain_mix_48x48;
    case 64: return wi_66_rain_mix_64x64;
    default:
      return nullptr;
    }
  case wi_71_snow_wind:
    switch (size) {
    case 16: return wi_71_snow_wind_16x16;
    case 24: return wi_71_snow_wind_24x24;
    case 32: return wi_71_snow_wind_32x32;
    case 48: return wi_71_snow_wind_48x48;
    case 64: return wi_71_snow_wind_64x64;
    default:
      return nullptr;
    }
  case wi_77_day_snow_wind:
    switch (size) {
    case 16: return wi_77_day_snow_wind_16x16;
    case 24: return wi_77_day_snow_wind_24x24;
    case 32: return wi_77_day_snow_wind_32x32;
    case 48: return wi_77_day_snow_wind_48x48;
    case 64: return wi_77_day_snow_wind_64x64;
    default:
      return nullptr;
    }
  case wi_81_showers:
    switch (size) {
    case 16: return wi_81_showers_16x16;
    case 24: return wi_81_showers_24x24;
    case 32: return wi_81_showers_32x32;
    case 48: return wi_81_showers_48x48;
    case 64: return wi_81_showers_64x64;
    default:
      return nullptr;
    }
  case wi_85_snow_wind:
    switch (size) {
    case 16: return wi_85_snow_wind_16x16;
    case 24: return wi_85_snow_wind_24x24;
    case 32: return wi_85_snow_wind_32x32;
    case 48: return wi_85_snow_wind_48x48;
    case 64: return wi_85_snow_wind_64x64;
    default:
      return nullptr;
    }
  case wi_95_thunderstorm:
    switch (size) {
    case 16: return wi_95_thunderstorm_16x16;
    case 24: return wi_95_thunderstorm_24x24;
    case 32: return wi_95_thunderstorm_32x32;
    case 48: return wi_95_thunderstorm_48x48;
    case 64: return wi_95_thunderstorm_64x64;
    default:
      return nullptr;
    }
  case wi_99_thunderstorm:
    switch (size) {
    case 16: return wi_99_thunderstorm_16x16;
    case 24: return wi_99_thunderstorm_24x24;
    case 32: return wi_99_thunderstorm_32x32;
    case 48: return wi_99_thunderstorm_48x48;
    case 64: return wi_99_thunderstorm_64x64;
    default:
      return nullptr;
    }
  case wi_cloud_down:
    switch (size) {
    case 16: return wi_cloud_down_16x16;
    case 24: return wi_cloud_down_24x24;
    case 32: return wi_cloud_down_32x32;
    case 48: return wi_cloud_down_48x48;
    case 64: return wi_cloud_down_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_full:
    switch (size) {
    case 16: return wi_moon_alt_full_16x16;
    case 24: return wi_moon_alt_full_24x24;
    case 32: return wi_moon_alt_full_32x32;
    case 48: return wi_moon_alt_full_48x48;
    case 64: return wi_moon_alt_full_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_third_quarter:
    switch (size) {
    case 16: return wi_moon_alt_third_quarter_16x16;
    case 24: return wi_moon_alt_third_quarter_24x24;
    case 32: return wi_moon_alt_third_quarter_32x32;
    case 48: return wi_moon_alt_third_quarter_48x48;
    case 64: return wi_moon_alt_third_quarter_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_4:
    switch (size) {
    case 16: return wi_moon_alt_waning_crescent_4_16x16;
    case 24: return wi_moon_alt_waning_crescent_4_24x24;
    case 32: return wi_moon_alt_waning_crescent_4_32x32;
    case 48: return wi_moon_alt_waning_crescent_4_48x48;
    case 64: return wi_moon_alt_waning_crescent_4_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_5:
    switch (size) {
    case 16: return wi_moon_alt_waning_crescent_5_16x16;
    case 24: return wi_moon_alt_waning_crescent_5_24x24;
    case 32: return wi_moon_alt_waning_crescent_5_32x32;
    case 48: return wi_moon_alt_waning_crescent_5_48x48;
    case 64: return wi_moon_alt_waning_crescent_5_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_crescent_6:
    switch (size) {
    case 16: return wi_moon_alt_waning_crescent_6_16x16;
    case 24: return wi_moon_alt_waning_crescent_6_24x24;
    case 32: return wi_moon_alt_waning_crescent_6_32x32;
    case 48: return wi_moon_alt_waning_crescent_6_48x48;
    case 64: return wi_moon_alt_waning_crescent_6_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_1:
    switch (size) {
    case 16: return wi_moon_alt_waning_gibbous_1_16x16;
    case 24: return wi_moon_alt_waning_gibbous_1_24x24;
    case 32: return wi_moon_alt_waning_gibbous_1_32x32;
    case 48: return wi_moon_alt_waning_gibbous_1_48x48;
    case 64: return wi_moon_alt_waning_gibbous_1_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_2:
    switch (size) {
    case 16: return wi_moon_alt_waning_gibbous_2_16x16;
    case 24: return wi_moon_alt_waning_gibbous_2_24x24;
    case 32: return wi_moon_alt_waning_gibbous_2_32x32;
    case 48: return wi_moon_alt_waning_gibbous_2_48x48;
    case 64: return wi_moon_alt_waning_gibbous_2_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_3:
    switch (size) {
    case 16: return wi_moon_alt_waning_gibbous_3_16x16;
    case 24: return wi_moon_alt_waning_gibbous_3_24x24;
    case 32: return wi_moon_alt_waning_gibbous_3_32x32;
    case 48: return wi_moon_alt_waning_gibbous_3_48x48;
    case 64: return wi_moon_alt_waning_gibbous_3_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_4:
    switch (size) {
    case 16: return wi_moon_alt_waning_gibbous_4_16x16;
    case 24: return wi_moon_alt_waning_gibbous_4_24x24;
    case 32: return wi_moon_alt_waning_gibbous_4_32x32;
    case 48: return wi_moon_alt_waning_gibbous_4_48x48;
    case 64: return wi_moon_alt_waning_gibbous_4_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_5:
    switch (size) {
    case 16: return wi_moon_alt_waning_gibbous_5_16x16;
    case 24: return wi_moon_alt_waning_gibbous_5_24x24;
    case 32: return wi_moon_alt_waning_gibbous_5_32x32;
    case 48: return wi_moon_alt_waning_gibbous_5_48x48;
    case 64: return wi_moon_alt_waning_gibbous_5_64x64;
    default:
      return nullptr;
    }
  case wi_moon_alt_waning_gibbous_6:
    switch (size) {
    case 16: return wi_moon_alt_waning_gibbous_6_16x16;
    case 24: return wi_moon_alt_waning_gibbous_6_24x24;
    case 32: return wi_moon_alt_waning_gibbous_6_32x32;
    case 48: return wi_moon_alt_waning_gibbous_6_48x48;
    case 64: return wi_moon_alt_waning_gibbous_6_64x64;
    default:
      return nullptr;
    }
  case wi_moon_full:
    switch (size) {
    case 16: return wi_moon_full_16x16;
    case 24: return wi_moon_full_24x24;
    case 32: return wi_moon_full_32x32;
    case 48: return wi_moon_full_48x48;
    case 64: return wi_moon_full_64x64;
    default:
      return nullptr;
    }
  case wi_strong_wind:
    switch (size) {
    case 16: return wi_strong_wind_16x16;
    case 24: return wi_strong_wind_24x24;
    case 32: return wi_strong_wind_32x32;
    case 48: return wi_strong_wind_48x48;
    case 64: return wi_strong_wind_64x64;
    default:
      return nullptr;
    }
  case wi_sunrise:
    switch (size) {
    case 16: return wi_sunrise_16x16;
    case 24: return wi_sunrise_24x24;
    case 32: return wi_sunrise_32x32;
    case 48: return wi_sunrise_48x48;
    case 64: return wi_sunrise_64x64;
    default:
      return nullptr;
    }
  case wi_sunset:
    switch (size) {
    case 16: return wi_sunset_16x16;
    case 24: return wi_sunset_24x24;
    case 32: return wi_sunset_32x32;
    case 48: return wi_sunset_48x48;
    case 64: return wi_sunset_64x64;
    default:
      return nullptr;
    }
  case wi_time_5:
    switch (size) {
    case 16: return wi_time_5_16x16;
    case 24: return wi_time_5_24x24;
    case 32: return wi_time_5_32x32;
    case 48: return wi_time_5_48x48;
    case 64: return wi_time_5_64x64;
    default:
      return nullptr;
    }
  case wifi:
    switch (size) {
    case 16: return wifi_16x16;
    case 24: return wifi_24x24;
    case 32: return wifi_32x32;
    case 48: return wifi_48x48;
    case 64: return wifi_64x64;
    default:
      return nullptr;
    }
  case wifi_1_bar:
    switch (size) {
    case 16: return wifi_1_bar_16x16;
    case 24: return wifi_1_bar_24x24;
    case 32: return wifi_1_bar_32x32;
    case 48: return wifi_1_bar_48x48;
    case 64: return wifi_1_bar_64x64;
    default:
      return nullptr;
    }
  case wifi_2_bar:
    switch (size) {
    case 16: return wifi_2_bar_16x16;
    case 24: return wifi_2_bar_24x24;
    case 32: return wifi_2_bar_32x32;
    case 48: return wifi_2_bar_48x48;
    case 64: return wifi_2_bar_64x64;
    default:
      return nullptr;
    }
  case wifi_3_bar:
    switch (size) {
    case 16: return wifi_3_bar_16x16;
    case 24: return wifi_3_bar_24x24;
    case 32: return wifi_3_bar_32x32;
    case 48: return wifi_3_bar_48x48;
    case 64: return wifi_3_bar_64x64;
    default:
      return nullptr;
    }
  case wifi_off:
    switch (size) {
    case 16: return wifi_off_16x16;
    case 24: return wifi_off_24x24;
    case 32: return wifi_off_32x32;
    case 48: return wifi_off_48x48;
    case 64: return wifi_off_64x64;
    default:
      return nullptr;
    }
  default:
    return nullptr;
  }
}

#endif
