#!/usr/bin/env python3
"""
Convert data/config_my_station.html → include/config/config_page_html.h

Generates a C header with the HTML content as a PROGMEM raw string literal.
Run manually after editing the HTML, or automatically via PlatformIO pre-build script.

Usage:
    python3 tools/embed_html.py
    # or via PlatformIO extra_scripts (called automatically before build)
"""

import os
import sys


def get_project_root():
    """Get project root - works both as CLI script and PlatformIO SCons script."""
    # When run via PlatformIO SCons, __file__ may not be defined
    # Use the script path from sys.argv or fall back to cwd-based detection
    try:
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    except NameError:
        # Running inside PlatformIO SCons - use env or cwd
        return os.getcwd()


def generate_header(project_root):
    html_source = os.path.join(project_root, "data", "config_my_station.html")
    header_output = os.path.join(project_root, "include", "config", "config_page_html.h")

    if not os.path.exists(html_source):
        print(f"ERROR: Source HTML not found: {html_source}", file=sys.stderr)
        sys.exit(1)

    with open(html_source, "r", encoding="utf-8") as f:
        html_content = f.read()

    header = (
        '// AUTO-GENERATED by tools/embed_html.py — DO NOT EDIT\n'
        '// Source: data/config_my_station.html\n'
        '#pragma once\n'
        '\n'
        '#include <pgmspace.h>\n'
        '\n'
        'static const char CONFIG_PAGE_HTML[] PROGMEM = R"HTMLRAW(\n'
        f'{html_content}\n'
        ')HTMLRAW";\n'
    )

    # Only write if content changed (avoid unnecessary rebuilds)
    if os.path.exists(header_output):
        with open(header_output, "r", encoding="utf-8") as f:
            if f.read() == header:
                print(f"embed_html: {header_output} is up to date")
                return

    with open(header_output, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"embed_html: Generated {header_output} ({len(html_content)} bytes HTML)")


# PlatformIO pre-build script entry point
try:
    Import("env")
    # Running inside PlatformIO SCons
    project_dir = env.subst("$PROJECT_DIR")
    generate_header(project_dir)
except Exception:
    # Running as standalone CLI script
    if __name__ == "__main__":
        generate_header(get_project_root())
