"""
PlatformIO pre-build script: Embeds HTML templates into a C++ header as PROGMEM.

This ensures the config page HTML is included in the firmware binary,
so OTA firmware updates automatically deliver the latest HTML template.

Usage in platformio.ini:
    extra_scripts = pre:tools/embed_html.py
"""

Import("env")
import os

def embed_html(source, target, env):
    project_dir = env.get("PROJECT_DIR")
    html_path = os.path.join(project_dir, "data", "config_my_station.html")
    output_path = os.path.join(project_dir, "include", "config", "config_page_html.h")

    if not os.path.exists(html_path):
        print(f"WARNING: {html_path} not found, skipping HTML embed")
        return

    # Check if output is up-to-date
    if os.path.exists(output_path):
        if os.path.getmtime(output_path) >= os.path.getmtime(html_path):
            return  # Already up-to-date

    with open(html_path, "r", encoding="utf-8") as f:
        html_content = f.read()

    # Escape for C++ raw string literal (R"rawdelim(...)rawdelim")
    # Raw strings can contain anything except the closing delimiter sequence
    # We use a unique delimiter to avoid conflicts
    delimiter = "HTMLRAW"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/embed_html.py — DO NOT EDIT\n")
        f.write("// Source: data/config_my_station.html\n")
        f.write("#pragma once\n\n")
        f.write(f'static const char CONFIG_PAGE_HTML[] PROGMEM = R"{delimiter}(\n')
        f.write(html_content)
        f.write(f'\n){delimiter}";\n')

    print(f"Embedded HTML ({len(html_content)} bytes) -> {output_path}")

# Register pre-build action
env.AddPreAction("buildprog", embed_html)

